import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans", subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App", description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>)
{
  return (<html lang="en" className="h-full">
  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased h-full flex flex-col`}
  >
  <h1 className="bg-[#ADB5BD] p-2 text-3xl font-bold flex justify-center">
    MyFlix
  </h1>

  <main className="flex-1">
    {children}
  </main>

  <footer className="bg-[#495057] text-white text-center p-4 mb-0">
    <p className="text-sm">
      © {new Date().getFullYear()} MyFlix. Projeto de teste técnico.
    </p>
  </footer>
  </body>
  </html>);
}